---

- hosts: localhost

  tasks:

        - name: Install dependencies
          pip:
                    name: docker
                    state: presentce .

        - name: Install docker-compose
          pip:
                    name: docker-compose
                    state: present        
          

        - name: Run using a project directory
          hosts: localhost
          gather_facts: no
          tasks:
                - name: Tear down existing services
                  docker_compose:
                        project_src: flask
                        state: absent
