---

- hosts: local

  tasks:
        - name: Install docker
          pip:
                    name: docker
                    state: present

        
         - name: run tools in docker container
            docker_container:
                    name: site1
                    hostname: site1
                    image: testkb
                    state: started
                    pull: no
                    exposed_ports:
                      - 8089
                    volumes:
                      - /data
              
