version: '2'
services:
   logicaldoc3:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8083:8080
      environment: 
        - dbms=mysql
        - username=logicaldocuser
        - password=logicaldocpassword
        - driver=com.mysql.jdbc.Driver
        - dialect=org.hibernate.dialect.MySQLDialect
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:mysql://db_mysql_3:3307/logicaldoc
        - JHIPSTER_SLEEP=10
   db_mysql_3:
      build:
        context: .
        dockerfile : mysql.Dockerfile
      environment:
        - MYSQL_ROOT_PASSWORD=logicaldocuser
        - MYSQL_USER=logicaldocuser
        - MYSQL_PASSWORD=logicaldocpassword
        - MYSQL_DATABASE=logicaldoc
      ports: 
        - 3307:3306