version: '2'
services:
   main:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8081:8080
      environment: 
        - dbms=mysql
        - username=logicaldocuser
        - password=logicaldocpassword
        - driver=com.mysql.jdbc.Driver
        - dialect=org.hibernate.dialect.MySQLDialect
        - SPRING_PROFILES_ACTIVE=prod,swagger
        - SPRING_DATASOURCE_URL=jdbc:mysql://app_mysql:3306/logicaldoc
        - JHIPSTER_SLEEP=10
   app_mysql:
      build:
        context: .
        dockerfile : mysql.Dockerfile
      environment:
        - MYSQL_ROOT_PASSWORD=logicaldocuser
        - MYSQL_USER=logicaldocuser
        - MYSQL_PASSWORD=logicaldocpassword
        - MYSQL_DATABASE=logicaldoc
      ports: 
        - 3306:3306