---




version: '2'
services:
    logicaldoc:
        image: logicaldoc
        depends_on: 
          - postgres
        environment:
            USER: logicaldocuser
            PASSWORD: logicaldocpassword
            DB: logicaldocdb
        ports: 
            - 8081:8080/tcp
        links:
            - postgres
        #networks: 
            #- reseau_auto_postgres
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: logicaldocuser
            POSTGRES_PASSWORD: logicaldocpassword
            POSTGRES_DB: logicaldocdb
        volumes:
        - monvolume:/var/lib/postgresql/data
        #networks: 
            #- reseau_auto_postgres
volumes: 
    monvolume:
#networks:
    #reseau_auto_postgres
