---
- hosts: local

  tasks:

 
    - name: Only run equivalent apt-get update, if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

   
    - name: Install firefox 
      apt:
          name: firefox-esr   
          state: present

    - name: Download Google chrome
      get_url:
          url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dest: /opt/google-chrome.deb
    
    - name: Install Google chrome
      shell:
          cmd: apt install -y /opt/google-chrome.deb


    - name: Download and unarchive soapui
      unarchive :
           src: https://s3.amazonaws.com/downloads.eviware/soapuios/5.4.0/SoapUI-5.4.0-linux-bin.tar.gz 
           dest: /opt
           remote_src: yes

    
    - name: Enable snaps on Debian 9 to install SQuirrel SQL
      apt:
        name: snapd
        state: present

    - name: Install zaproxy
      shell:
        cmd: snap install zaproxy --classic
    
    - name: run the site in a docker container
      docker_container:
        name: site1
        image: testkb
        state: started
        pull: no
        exposed_ports:
          - 8089
        volumes:
          - /data
    
    - name: start ssh
      shell: for ct in $(docker ps -q) ; do docker exec -t $ct service ssh start ; done
        
        







