---
hosts: todo

  tasks:

    - name: Only run equivalent apt-get update, if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install xfce4 goodies for vnc
      apt:
        name: xfce4 xfce4-goodies #find how to select a langage automaticaly and entree
        state: present

    - name: Install tightvncserver
      apt:
        name: tightvncserver
        state: present



#to do configure password : commande vncserver password 6 to 8 char,  verify
